docker: Fix SWH jobs execution on local Jenkins testing instance
Due to different UIDs for the jenkins user and different GIDs for
the docker group between the jenkins container and the SWH container
used to execute Jenkins pipelines, the jobs were failing due to
permission errors.

So ensure to use the same UIDs and GIDs as in SWH container for the
jenkins container and forward docker host GID in every started
container in order to fix those issues.

Also remove docker stack installation in jenkins container as it is
not needed, use docker host stack instead.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -2,20 +2,23 @@ FROM jenkins/jenkins:jdk11
 
 USER root
 
+# use same uid and gid for jenkins user/group as in SWH docker images
+# (https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-jenkins-dockerfiles)
+# used in jenkins jobs to avoid permission errors when running docker
+# in jenkins pipelines
+RUN groupmod -g 120 jenkins
+RUN usermod -u 115 -g 120 jenkins
+RUN find / -group 1000 -exec chgrp -h jenkins '{}' \; || true
+RUN find / -user 1000 -exec chown -h jenkins '{}' \; || true
+
+# install tox required to bootstrap jenkins jobs configuration
 RUN apt-get update && apt-get -y install tox
 
-# Adapt this group if the docker gid is not 999 on your local environment
+# adapt this group if the docker gid is not 998 on your local environment
 ARG DOCKER_GROUP=998
 
-# Install docker tools
-RUN addgroup --gid ${DOCKER_GROUP} docker && \
-    mkdir -p /etc/apt/keyrings /etc/apt/sources.list.d && \
-    apt-get update && apt-get -y install ca-certificates curl gnupg lsb-release && \
-    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
-    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
-    apt-get update && \
-    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
-
+# add jenkins user to docker group
+RUN addgroup --gid ${DOCKER_GROUP} docker
 RUN adduser jenkins docker
 
 USER jenkins
