jobs/swh-environment: Optimize rust compilation in production jenkins
Use local cargo cache for crates code, remote sccache for the compiled
crates and do not compile in release mode.

diff --git a/jobs/templates/swh-environment.groovy.j2 b/jobs/templates/swh-environment.groovy.j2
--- a/jobs/templates/swh-environment.groovy.j2
+++ b/jobs/templates/swh-environment.groovy.j2
@@ -30,54 +30,63 @@ pipeline {
     stage('Run tests') {
 
       steps {
-        sh '''#!/bin/bash
-          # Don't fetch potentially large branches, we only need master
-          sed -i 's/git clone/git clone --single-branch/g' .mrconfig
-          # fetch swh repositories
-          mr -j 4 -t update
-          # setup a virtualenv
-          python{{python_version}} -m venv .venv
-          source .venv/bin/activate
-          # upgrade pip as default installed version is too outdated to properly
-          # install all swh dependencies
-          pip install --upgrade pip
-          # install dependencies
-          ./bin/install
-          (cd swh-graph &&
-           cargo build --all-features &&
-           cargo build --release --all-features)
-          (cd swh-web && yarn install)
-          # execute tests in each swh module
-          pip install pytest-xdist
-          exit_code=0
-          swh_env_dir=$PWD
-          for module in $(./bin/ls-py-modules); do
-            cd $swh_env_dir/$module
-            echo Executing $module checks and tests
-            tests_dir=$(echo $module | sed 's/-/\\//g')/tests
-            if [ -d "$tests_dir" ]; then
-              # enable parallel tests execution except for scanner
-              if [ "$module" != "swh-scanner" ]; then
-                export TESTFLAGS="-n auto"
-              else
-                export TESTFLAGS=
+        {% if production_jenkins %}
+        withCredentials([
+          string(credentialsId: 'sccache-redis-endpoint', variable: 'SCCACHE_REDIS_ENDPOINT'),
+          string(credentialsId: 'sccache-redis-password', variable: 'SCCACHE_REDIS_PASSWORD'),
+        ]) {
+        {% endif %}
+          sh '''#!/bin/bash
+            # Don't fetch potentially large branches, we only need master
+            sed -i 's/git clone/git clone --single-branch/g' .mrconfig
+            # fetch swh repositories
+            mr -j 4 -t update
+            # setup a virtualenv
+            python{{python_version}} -m venv .venv
+            source .venv/bin/activate
+            # upgrade pip as default installed version is too outdated to properly
+            # install all swh dependencies
+            pip install --upgrade pip
+            # install dependencies
+            ./bin/install
+            (cd swh-graph &&
+             prepare-cargo-cache &&
+             RUSTC_WRAPPER=sccache CARGO_INCREMENTAL=0 cargo build --all-features)
+            (cd swh-web && yarn install)
+            # execute tests in each swh module
+            pip install pytest-xdist
+            exit_code=0
+            swh_env_dir=$PWD
+            for module in $(./bin/ls-py-modules); do
+              cd $swh_env_dir/$module
+              echo Executing $module checks and tests
+              tests_dir=$(echo $module | sed 's/-/\\//g')/tests
+              if [ -d "$tests_dir" ]; then
+                # enable parallel tests execution except for scanner
+                if [ "$module" != "swh-scanner" ]; then
+                  export TESTFLAGS="-n auto"
+                else
+                  export TESTFLAGS=
+                fi
+                # pipe checks and tests output to stdout and log file
+                make check 2>&1 | tee ../$module.log
+                tests_status=${PIPESTATUS[0]}
+                make test 2>&1 | tee -a ../$module.log
+                tests_status=$(($tests_status + ${PIPESTATUS[0]}))
+                # remove log file if tests succeeded
+                if [ "$tests_status" -eq 0 ]; then
+                  rm -f ../$module.log
+                fi
+                # script must be exited with error when a test suite failed
+                exit_code=$(( tests_status > exit_code ? tests_status : exit_code ))
               fi
-              # pipe checks and tests output to stdout and log file
-              make check 2>&1 | tee ../$module.log
-              tests_status=${PIPESTATUS[0]}
-              make test 2>&1 | tee -a ../$module.log
-              tests_status=$(($tests_status + ${PIPESTATUS[0]}))
-              # remove log file if tests succeeded
-              if [ "$tests_status" -eq 0 ]; then
-                rm -f ../$module.log
-              fi
-              # script must be exited with error when a test suite failed
-              exit_code=$(( tests_status > exit_code ? tests_status : exit_code ))
-            fi
-          done
+            done
 
-          exit $exit_code
-        '''
+            exit $exit_code
+          '''
+        {% if production_jenkins %}
+        }
+        {% endif %}
       }
     }
   }
